### ISSUE TITLE
سایز صفحه

### ISSUE THREAD

**Issue by aliafshany** [MRT-77/AdobeConnectRecord#1]
سلام
آقا میخواستم یک تشکری بکنم واقعا چقدرر راحت تر کردی کارمارو
دمت گرم
میخواستم یک باگی رو بگم.
![Screen Shot 2021-12-11 at 14 20 04](https://user-images.githubusercontent.com/40741745/145673847-d38a083c-b906-493c-9c90-5cc4841e71ef.png)

من تنظیمات رو گذاشتم روی پر کیفیت ترین حالت ولی تا گزیه ضبط رو که میزنی سایز برنامه کوچک میشه و در نهایت یک فایل ویدیویی در همون حد و اندازه تحویل میده
در واقع عملن نمیشه در صفحه چیزی دید
![Screen Shot 2021-12-11 at 14 21 49](https://user-images.githubusercontent.com/40741745/145673889-f9057935-657a-4cb6-b51f-963048c2c994.png)

هرچند که تا همین اندازشم فوق العادس
ممنون

**Comment by MRT-77** [comment]
سلام
خوشحالم که برنامه براتون مفید بوده

توی توضیحات هم ذکر کردم که فقط قابلیت ضبط توی برنامه رو فعال میکنه در اصل اگر مشکلی حس میکنید که وجود داره باید نسخه adobe connect client خودتون بروز رسانی کنید.

در ضمن متوجه شدم برنامه adobe connect client توانایی تبدیل رو نداره و در واقع در حین پخش از صفحه ی خودش ضبط میکنه به همین دلیل نباید سایز پنجره رو دستی تغییر بدید و توسط تنظیمات میتونید کیفیت رو تعیین کنید تا سایز پنجره به اون مقدار تنظیم بشه و شروع به ضبط کنه.

همچنین در صورت استفاده از دکمه ![image](https://user-images.githubusercontent.com/40250976/145693383-fabf75ab-8641-4b20-989d-6a79556ef7c3.png) میتونید یکی از بخش ها رو به صورت تمام صفحه در کادر خود برنامه نمایش بدید و فقط اون بخش رو ضبط کنید.


موفق باشید.
