### ISSUE TITLE
compile Problem

### ISSUE THREAD

**Issue by valipour** [MRT-77/AdobeConnectRecord#2]
it has problem in compiling 
which  vs.net you used?
can you compile it  and send exe file?

**Comment by aliafshany** [comment]
the .exe file is in the release page.

https://github.com/MRT-77/AdobeConnectRecord/releases/download/v1.1/connect.exe

**Comment by MRT-77** [comment]
This software is written using **.net framework v4.0** and you can develop it in **visual studio 2015 v3** and newer.
Also the exe file is available in the [release](https://github.com/MRT-77/AdobeConnectRecord/releases) section.
