### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aliafshany** [MRT-77/AdobeConnectRecord#4]
سلام
امیدوارم که حالتون خوب باشه.
میخواستم به اطلاعاتون برسونم موقعی که ضبط  داره انجام میشه, بعد از مدتی, حتا ۹۵ درصد مونده به پایان جلسه, یک دفعه کرش میکنه.

ادوبی کانکت رو اپدیت کردم, نسخه های قدیمش رو هم ریختم ولی همچنان چیزی عوض نشد.
در تسک منیجر higher priority هم شده ولی همچنان همین وضعه.

آیا میتونید راهکاری پیشنهاد بدید و یا راهنماییم کنید؟

ممنون

ادیت:  باید هر دو برنامه adobeconnect  و  connect رو high  کرد

**Comment by MRT-77** [comment]
سلام
سپاس
مکانیز فعلی نرم افزار کار خاصی انجام نمیده و دسترسی به نحوه عمل کرد برنامه اصلی نداره.
در آینده قصد دارم روش دیگه ای برای دانلود جلسات انجام بدم ولی در حال حاظر کاری که باید انجام بدید این هست که جلوی منقضی شدن نشست (Session) رو از طریق رفرش کردن تب مرورگر بگیرید و در صورتی که این روش جواب نداد متاسفانه راه دیگه ای فعلا وجود نداره.
موفق باشید.

**Comment by aliafshany** [comment]
سلام.
بله این مورد رو حل کردم در نهایت.
امیدوارم روش دیگه رو بزودی منتشر کنید.

ممنونم ازتون
