### ISSUE TITLE
مشکل در نصب و اجرای برنامه

### ISSUE THREAD

**Issue by mahnazEhyaei** [MRT-77/AdobeConnectRecord#5]
با سلام و خسته نباشید
برای اجرای برنامه تمام مراحل نصب  و اجرای برنامه را انجام دادم. تغییر نام فایل به adobeconnect.exe هم انجام شد ولی بعد از اجرای یک وبینار برنامه adobe Connect  دیگر اجرا نمیشود که این فکر میکنم به خاطر تغییر نام فایل اصلی برنامه باشد. 
ممنون میشوم راهنمایی بفرمایید

**Comment by MRT-77** [comment]
سلام، زنده باشید
بعد از تغییر نام برنامه، فایلی که از این قسمت دانلود کردید کپی شده؟
در صورتی که امکان داره از پوشه نصب برنامه screen shot ارسال کنید.

ضمن اطلاع این ترفند روی وبینار های زنده قابل استفاده نیست اما مشکلی در اجرای برنامه هم ایجاد نمیکند.

**Comment by mahnazEhyaei** [comment]
سلام مجدد
ممنون از پاسخگویی شما
![Capture](https://user-images.githubusercontent.com/99958864/154671675-12412537-749c-4749-898c-5f8468cafdf3.JPG)
وبینارها آنلاین نیست و قبلا رکورد شده.

**Comment by mahnazEhyaei** [comment]
سلام مجدد
ممنون از پاسخگویی شما
مشکلم برطرف شد و برنامه به خوبی کار میکند.
سپاسگزارم از برنامه خوبتون
موفق باشید

**Comment by MRT-77** [comment]
بسیار عالی
موفق باشید

**Comment by am111n** [comment]
سلام. کل فایل های شما رو در فولدر نصب ادوب کانکت کپی کردم و فایل اصلی رو هم تغییر نام دادم. اما بعد از باز کردن لینک، هیچ پیامی برای دانلود نمایش داده نمیشه
